global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.1.231  # Closet Switch
        - 192.168.1.253 # Wifi AP
        - 192.168.1.105 # Family Room Switch
    metrics_path: /snmp
    params:
      module: [ubiquiti_unifi]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'synology_snmp'
    metrics_path: /snmp
    params:
      module: [ synology ]
    static_configs:
      - targets:
        - 192.168.1.16 # Diskstation
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.20:9100']
  - job_name: 'torrent'
    static_configs:
      - targets: ['downloader_exporter:9000']
  - job_name: 'media'
    static_configs:
      - targets: ['jellyfin.1ez.us:443']
    metrics_path: '/metrics'
    scheme: https
